# Generated by Django 3.2 on 2021-04-27 02:46

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, validators=[django.core.validators.MinLengthValidator(2), django.core.validators.MaxLengthValidator(30), django.core.validators.RegexValidator('^[A-Za-z,& ]{3,30}$'), django.core.validators.ProhibitNullCharactersValidator()])),
                ('description', models.CharField(max_length=250, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(250), django.core.validators.RegexValidator(message='Semicolons are not allowed.', regex='^[^;]{1,250}$'), django.core.validators.ProhibitNullCharactersValidator()])),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(2), django.core.validators.MaxLengthValidator(50), django.core.validators.RegexValidator("^[A-Za-z0-9,'%&:\\-\\.\\(\\) ]{2,50}$"), django.core.validators.ProhibitNullCharactersValidator()])),
                ('weight', models.DecimalField(decimal_places=2, default=1, max_digits=6, validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.MaxValueValidator(5000)])),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=7, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99999.99)])),
                ('description', models.CharField(max_length=250, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(250), django.core.validators.RegexValidator(message='Semicolons are not allowed.', regex='^[^;]{1,250}$'), django.core.validators.ProhibitNullCharactersValidator()])),
                ('quantity', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.category')),
            ],
        ),
    ]
