# Generated by Django 3.2 on 2021-05-02 04:02

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^[A-Z]+$')])),
                ('model_id', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('action', models.CharField(max_length=6, validators=[django.core.validators.RegexValidator('^(Create|Update|Delete)$')])),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ('-timestamp',),
            },
        ),
    ]
